server:
  port: 9999
 
spring:
  application:
    name: greeting-service
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
 
greeting-service:
  greeting: "Teste"    
  default-value: "Mundo"
