spring:
  application:
    name: greeting-service
  cloud:
    config:
      profile: perf    
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
greeting-service:
  greeting: "teste"
  default-value: "World"
